import { BlogPost, Product, TeamMember, CareerListing } from "./types";

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "b1",
    title: "Shipping our new component library",
    slug: "shipping-our-new-component-library",
    imageUrl: "",
    content: "Lorem ipsum...",
    author: "Ajay Tamang",
    category: "Tech",
    published: true,
    readMinutes: 4,
    createdAt: "2026-07-12T00:00:00.000Z",
    updatedAt: "2026-07-12T00:00:00.000Z",
  },
  {
    id: "b2",
    title: "How we structure Next.js apps at scale",
    slug: "how-we-structure-nextjs-apps-at-scale",
    imageUrl: "",
    content: "Lorem ipsum...",
    author: "Ajay Tamang",
    category: "Tech",
    published: false,
    readMinutes: 6,
    createdAt: "2026-07-28T00:00:00.000Z",
    updatedAt: "2026-07-28T00:00:00.000Z",
  },
  {
    id: "b3",
    title: "Behind the brand refresh",
    slug: "behind-the-brand-refresh",
    imageUrl: "",
    content: "Lorem ipsum...",
    author: "Sabina Rai",
    category: "Design",
    published: true,
    readMinutes: 3,
    createdAt: "2026-06-30T00:00:00.000Z",
    updatedAt: "2026-06-30T00:00:00.000Z",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Starter Plan",
    slug: "starter-plan",
    tagline: "Get started for free",
    problem: "Teams need an easy on-ramp.",
    features: ["Basic features"],
    technologies: ["Next.js"],
    previewUrl: "",
    productUrl: "https://example.com",
    featured: false,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "p2",
    name: "Pro Plan",
    slug: "pro-plan",
    tagline: "For growing teams",
    problem: "Teams outgrow the starter plan.",
    features: ["Advanced features"],
    technologies: ["Next.js"],
    previewUrl: "",
    productUrl: "https://example.com",
    featured: true,
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "p3",
    name: "On-site Workshop",
    slug: "on-site-workshop",
    tagline: "Hands-on team training",
    problem: "Teams need in-person guidance.",
    features: ["Full-day session"],
    technologies: [],
    previewUrl: "",
    productUrl: "https://example.com",
    featured: false,
    status: "inactive",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "t1",
    name: "Sabina Rai",
    role: "Design Lead",
    bio: "Leads product design and creates thoughtful, user-focused digital experiences.",
    photo: "",
    socials: {
      linkedin: "https://linkedin.com/in/sabina-rai",
      github: "https://github.com/sabina-rai",
      email: "sabina@meta-tronix.com",
    },
  },
  {
    id: "t2",
    name: "Prakash Shrestha",
    role: "Backend Engineer",
    bio: "Builds reliable backend systems, APIs, and scalable application infrastructure.",
    photo: "",
    socials: {
      linkedin: "https://linkedin.com/in/prakash-shrestha",
      github: "https://github.com/prakash-shrestha",
      email: "prakash@meta-tronix.com",
    },
  },
  {
    id: "t3",
    name: "Nisha Gurung",
    role: "Marketing Associate",
    bio: "Works on brand communication, content strategy, and digital marketing initiatives.",
    photo: "",
    socials: {
      linkedin: "https://linkedin.com/in/nisha-gurung",
      github: "",
      email: "nisha@meta-tronix.com",
    },
  },
];

export const CAREER_LISTINGS: CareerListing[] = [
  {
    id: "c1",
    title: "Frontend Engineer Intern",
    department: "Engineering",
    location: "Kathmandu, NP",
    employmentType: "internship",
    workplace: "onsite",
    description: "Join our engineering team as an intern.",
    responsibilities: ["Build UI components"],
    requirements: ["Currently studying CS"],
    preferredQualifications: [],
    experience: "0-1 years",
    vacancies: 1,
    status: "open",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "c2",
    title: "Product Designer",
    department: "Design",
    location: "Remote",
    employmentType: "full-time",
    workplace: "remote",
    description: "Design delightful product experiences.",
    responsibilities: ["Design UI/UX flows"],
    requirements: ["3+ years experience"],
    preferredQualifications: [],
    experience: "3-5 years",
    vacancies: 1,
    status: "open",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "c3",
    title: "Content Writer",
    department: "Marketing",
    location: "Kathmandu, NP",
    employmentType: "part-time",
    workplace: "onsite",
    description: "Write compelling content for our brand.",
    responsibilities: ["Write blog posts"],
    requirements: ["Strong writing skills"],
    preferredQualifications: [],
    experience: "1-2 years",
    vacancies: 1,
    status: "closed",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];
